// The LIFE.EXE reference dataset: 500 real-life situations in 25 categories, each with the four follow-up
// questions people often ask next. Converted from the Word document "LIFE.EXE 500 Real-Life Situations and
// Follow-ups", keeping its numbering, categories and wording.
//
// The document writes every situation as "I'm dealing with <situation>. What should I do?" and lists four
// follow-up questions under it. Every situation in a category has the same four, so they're stored once per
// category here and attached to each of its situations in `REFERENCE_SITUATIONS`.
//
// This is reference material for the live AI, not a script. For each message, `retrieve` (match.ts) finds the
// few situations that resemble the conversation, if any, and `referenceContext` (context.ts) gives only those
// to Gemini as private guidance. None of it is shown to people, and Gemini still writes every answer.

export interface ReferenceCategory {
  /** Stable ID, also the start of its situations' IDs, for example "friends". */
  id: string;
  /** The category's name in the document, for example "Friends & Social Situations". */
  name: string;
  /** The four follow-up questions the document gives every situation in this category. */
  followUps: readonly string[];
}

export interface ReferenceSituation {
  /** Stable ID: the category ID and the situation's place in that category, for example "friends-01". */
  id: string;
  /** The situation's number in the document, from 1 to 500. */
  number: number;
  category: ReferenceCategory;
  /** The situation, as the document puts it after "I'm dealing with": "a friend acting distant and I cannot tell why". */
  situation: string;
  /** Its four follow-up questions, as the document lists them. */
  followUps: readonly string[];
}

type CategorySource = ReferenceCategory & { situations: Array<Pick<ReferenceSituation, "id" | "number" | "situation">> };

const DATASET: CategorySource[] = [
  {
    id: "school",
    name: "School & Classes",
    followUps: [
      "What should I do first?",
      "How can I make a simple plan?",
      "What if I still struggle after trying that?",
      "Who should I ask for help?",
    ],
    situations: [
      { id: "school-01", number: 1, situation: "falling behind in one subject even though I attend every class" },
      { id: "school-02", number: 2, situation: "forgetting lessons a few days after learning them" },
      { id: "school-03", number: 3, situation: "struggling because my teacher explains too quickly" },
      { id: "school-04", number: 4, situation: "making careless mistakes in work I actually understand" },
      { id: "school-05", number: 5, situation: "having several homework deadlines on the same day" },
      { id: "school-06", number: 6, situation: "being afraid to answer questions because I might be wrong" },
      { id: "school-07", number: 7, situation: "trying to catch up after missing several classes" },
      { id: "school-08", number: 8, situation: "finding a textbook chapter confusing even after reading it" },
      { id: "school-09", number: 9, situation: "getting distracted whenever I study at home" },
      { id: "school-10", number: 10, situation: "feeling slower than everyone else in class" },
      { id: "school-11", number: 11, situation: "finding it difficult to communicate with a particular teacher" },
      { id: "school-12", number: 12, situation: "forgetting books or materials I need for school" },
      { id: "school-13", number: 13, situation: "doing well in assignments but struggling in timed tests" },
      { id: "school-14", number: 14, situation: "deciding whether to take an optional school activity" },
      { id: "school-15", number: 15, situation: "classmates repeatedly asking for my homework answers" },
      { id: "school-16", number: 16, situation: "postponing a large school project until the deadline is close" },
      { id: "school-17", number: 17, situation: "receiving feedback on an assignment that feels unfair" },
      { id: "school-18", number: 18, situation: "having two school commitments at the same time" },
      { id: "school-19", number: 19, situation: "staying up late because I have too much schoolwork" },
      { id: "school-20", number: 20, situation: "feeling disconnected from my class and rarely talking to anyone" },
    ],
  },
  {
    id: "exams",
    name: "Exams & Test Pressure",
    followUps: [
      "What should I prioritize?",
      "How should I handle it during the exam?",
      "What should I change before the next test?",
      "What if I cannot fix everything in time?",
    ],
    situations: [
      { id: "exams-01", number: 21, situation: "having an exam soon but barely starting preparation" },
      { id: "exams-02", number: 22, situation: "studying hard and still getting a much lower score than expected" },
      { id: "exams-03", number: 23, situation: "panicking when I see a difficult question at the start of an exam" },
      { id: "exams-04", number: 24, situation: "spending too much time on the first few questions" },
      { id: "exams-05", number: 25, situation: "knowing the material at home but going blank in exams" },
      { id: "exams-06", number: 26, situation: "having several exams in the same week" },
      { id: "exams-07", number: 27, situation: "changing correct answers because I stop trusting myself" },
      { id: "exams-08", number: 28, situation: "losing marks because I do not read questions carefully" },
      { id: "exams-09", number: 29, situation: "wanting to study all night before an exam" },
      { id: "exams-10", number: 30, situation: "comparing my mock-test scores with my friends" },
      { id: "exams-11", number: 31, situation: "making the same type of mistake in every practice test" },
      { id: "exams-12", number: 32, situation: "not knowing whether to attempt a hard question or move on" },
      { id: "exams-13", number: 33, situation: "feeling guilty whenever I take a break during exam preparation" },
      { id: "exams-14", number: 34, situation: "making lots of notes but not doing enough practice questions" },
      { id: "exams-15", number: 35, situation: "forgetting formulas even after memorizing them" },
      { id: "exams-16", number: 36, situation: "doing badly on my first mock exam and losing confidence" },
      { id: "exams-17", number: 37, situation: "feeling pressure because my family expects a very high score" },
      { id: "exams-18", number: 38, situation: "not knowing whether to focus on weak topics or strong ones" },
      { id: "exams-19", number: 39, situation: "having a test immediately after a tiring school day" },
      { id: "exams-20", number: 40, situation: "finishing an exam and obsessing over the questions I may have missed" },
    ],
  },
  {
    id: "jee",
    name: "JEE & Competitive Preparation",
    followUps: [
      "What should I prioritize first?",
      "How should I fit this into my current routine?",
      "What if I am already behind?",
      "How can I tell whether the strategy is working?",
    ],
    situations: [
      { id: "jee-01", number: 41, situation: "balancing JEE preparation with a heavy school workload" },
      { id: "jee-02", number: 42, situation: "understanding a JEE concept but failing unfamiliar questions" },
      { id: "jee-03", number: 43, situation: "falling behind because coaching moves faster than I can understand" },
      { id: "jee-04", number: 44, situation: "having a large backlog of chapters" },
      { id: "jee-05", number: 45, situation: "solving easy questions while avoiding difficult ones" },
      { id: "jee-06", number: 46, situation: "having decent accuracy but very poor speed" },
      { id: "jee-07", number: 47, situation: "watching lectures instead of practicing enough" },
      { id: "jee-08", number: 48, situation: "getting confused by different teachers' methods" },
      { id: "jee-09", number: 49, situation: "collecting too many study resources and finishing none" },
      { id: "jee-10", number: 50, situation: "seeing my mock-test rank or percentile drop" },
      { id: "jee-11", number: 51, situation: "not knowing whether to revise theory or solve problems" },
      { id: "jee-12", number: 52, situation: "making frequent calculation errors in physics or chemistry" },
      { id: "jee-13", number: 53, situation: "being strong in one subject but avoiding my weakest one" },
      { id: "jee-14", number: 54, situation: "feeling overwhelmed by the amount of JEE material left" },
      { id: "jee-15", number: 55, situation: "restarting my study plan every Monday" },
      { id: "jee-16", number: 56, situation: "watching JEE strategy videos instead of studying" },
      { id: "jee-17", number: 57, situation: "not knowing when to stop struggling and check a solution" },
      { id: "jee-18", number: 58, situation: "having a coaching test and school exam on the same weekend" },
      { id: "jee-19", number: 59, situation: "feeling behind because other students started earlier" },
      { id: "jee-20", number: 60, situation: "not knowing whether my current JEE routine is actually working" },
    ],
  },
  {
    id: "friends",
    name: "Friends & Social Situations",
    followUps: [
      "Should I talk to them about it?",
      "What should I say?",
      "What if they react badly or do not reply?",
      "How do I know when to step back?",
    ],
    situations: [
      { id: "friends-01", number: 61, situation: "a friend acting distant and I cannot tell why" },
      { id: "friends-02", number: 62, situation: "a friend cancelling plans at the last minute repeatedly" },
      { id: "friends-03", number: 63, situation: "always being the person who starts conversations" },
      { id: "friends-04", number: 64, situation: "a friend telling me something private and someone else asking about it" },
      { id: "friends-05", number: 65, situation: "two friends arguing and both wanting me to take sides" },
      { id: "friends-06", number: 66, situation: "a joke I made upsetting a friend" },
      { id: "friends-07", number: 67, situation: "a friend constantly asking for favors without helping me back" },
      { id: "friends-08", number: 68, situation: "feeling left out when friends make plans without me" },
      { id: "friends-09", number: 69, situation: "a friend spending most of their time with a new group" },
      { id: "friends-10", number: 70, situation: "a friend turning normal conversations into competitions" },
      { id: "friends-11", number: 71, situation: "an argument making things awkward with a friend" },
      { id: "friends-12", number: 72, situation: "a friend giving advice when I only wanted them to listen" },
      { id: "friends-13", number: 73, situation: "a friend saying they are fine even though something seems different" },
      { id: "friends-14", number: 74, situation: "accidentally leaving a friend out of a group plan" },
      { id: "friends-15", number: 75, situation: "a friend venting to me so often that I feel drained" },
      { id: "friends-16", number: 76, situation: "wanting to become friends with someone in my class" },
      { id: "friends-17", number: 77, situation: "friends pressuring me to do something I am uncomfortable with" },
      { id: "friends-18", number: 78, situation: "finding out a friend complained about me to someone else" },
      { id: "friends-19", number: 79, situation: "a friend ignoring my messages while being active elsewhere" },
      { id: "friends-20", number: 80, situation: "feeling like my friend group is changing and I no longer fit" },
    ],
  },
  {
    id: "family",
    name: "Family & Home",
    followUps: [
      "How should I bring this up?",
      "What could I say without starting an argument?",
      "What if they disagree?",
      "Who else could help me handle it?",
    ],
    situations: [
      { id: "family-01", number: 81, situation: "arguing with my parents about how much time I spend on my phone" },
      { id: "family-02", number: 82, situation: "my family expecting me to study whenever I am resting" },
      { id: "family-03", number: 83, situation: "wanting more independence while my parents are worried about me" },
      { id: "family-04", number: 84, situation: "being compared with another student by my parents" },
      { id: "family-05", number: 85, situation: "making a mistake at home and being afraid to tell my parents" },
      { id: "family-06", number: 86, situation: "a sibling using my things without asking" },
      { id: "family-07", number: 87, situation: "my family schedule making my routine difficult" },
      { id: "family-08", number: 88, situation: "wanting to pursue an interest my family does not understand" },
      { id: "family-09", number: 89, situation: "my parents wanting me to choose a path I am unsure about" },
      { id: "family-10", number: 90, situation: "tension at home making it hard to concentrate" },
      { id: "family-11", number: 91, situation: "feeling responsible for keeping peace between family members" },
      { id: "family-12", number: 92, situation: "family members interrupting me while I study" },
      { id: "family-13", number: 93, situation: "needing to ask my parents for something expensive" },
      { id: "family-14", number: 94, situation: "family plans conflicting with important schoolwork" },
      { id: "family-15", number: 95, situation: "feeling like my family does not listen to my side" },
      { id: "family-16", number: 96, situation: "repeated arguments with a sibling over shared space" },
      { id: "family-17", number: 97, situation: "wanting to tell my family about school pressure" },
      { id: "family-18", number: 98, situation: "family plans conflicting with something important to me" },
      { id: "family-19", number: 99, situation: "feeling guilty about hobbies while schoolwork is unfinished" },
      { id: "family-20", number: 100, situation: "wanting to rebuild trust after breaking a household rule" },
    ],
  },
  {
    id: "communication",
    name: "Communication & Awkward Conversations",
    followUps: [
      "What should I actually say?",
      "Should I do it in person or by message?",
      "What if they react badly?",
      "When should I stop explaining?",
    ],
    situations: [
      { id: "communication-01", number: 101, situation: "needing to tell someone I cannot attend their event" },
      { id: "communication-02", number: 102, situation: "asking someone for help while feeling uncomfortable depending on them" },
      { id: "communication-03", number: 103, situation: "sending a message that sounded harsher than I intended" },
      { id: "communication-04", number: 104, situation: "giving someone feedback without hurting their feelings" },
      { id: "communication-05", number: 105, situation: "automatically saying yes when I actually want to say no" },
      { id: "communication-06", number: 106, situation: "asking a teacher for an extension" },
      { id: "communication-07", number: 107, situation: "telling a teammate they are not doing their part" },
      { id: "communication-08", number: 108, situation: "being repeatedly interrupted while speaking" },
      { id: "communication-09", number: 109, situation: "not knowing how to start a difficult conversation" },
      { id: "communication-10", number: 110, situation: "needing to apologize but not knowing what to say" },
      { id: "communication-11", number: 111, situation: "telling someone that their behavior is bothering me" },
      { id: "communication-12", number: 112, situation: "misunderstanding a message and reacting too quickly" },
      { id: "communication-13", number: 113, situation: "asking for clarification without wanting to look incompetent" },
      { id: "communication-14", number: 114, situation: "someone making plans for me without asking" },
      { id: "communication-15", number: 115, situation: "telling a group that their plan is unrealistic" },
      { id: "communication-16", number: 116, situation: "speaking to an unfamiliar adult about something important" },
      { id: "communication-17", number: 117, situation: "correcting someone who misunderstood what I said" },
      { id: "communication-18", number: 118, situation: "asking a friend whether something is wrong between us" },
      { id: "communication-19", number: 119, situation: "ending a favor I can no longer keep doing" },
      { id: "communication-20", number: 120, situation: "overthinking simple messages before sending them" },
    ],
  },
  {
    id: "confidence",
    name: "Confidence & Self-Doubt",
    followUps: [
      "How can I handle the feeling right now?",
      "What is one small action I can take?",
      "What if I still feel unsure?",
      "How can I build confidence over time?",
    ],
    situations: [
      { id: "confidence-01", number: 121, situation: "knowing I can do something but doubting myself before starting" },
      { id: "confidence-02", number: 122, situation: "comparing my progress with people who seem much better than me" },
      { id: "confidence-03", number: 123, situation: "turning one mistake into a belief that I am bad at something" },
      { id: "confidence-04", number: 124, situation: "being nervous about speaking in front of a group" },
      { id: "confidence-05", number: 125, situation: "feeling awkward when meeting new people" },
      { id: "confidence-06", number: 126, situation: "wanting to try something new but fearing I will be bad at it" },
      { id: "confidence-07", number: 127, situation: "replaying criticism in my head" },
      { id: "confidence-08", number: 128, situation: "freezing in unfamiliar groups even though I am confident with friends" },
      { id: "confidence-09", number: 129, situation: "worrying that everyone is judging me when I make mistakes" },
      { id: "confidence-10", number: 130, situation: "waiting to feel confident before taking action" },
      { id: "confidence-11", number: 131, situation: "being afraid to ask a question in class" },
      { id: "confidence-12", number: 132, situation: "doing well once and then fearing I cannot repeat it" },
      { id: "confidence-13", number: 133, situation: "feeling embarrassed about something I said yesterday" },
      { id: "confidence-14", number: 134, situation: "avoiding opportunities because someone else seems more qualified" },
      { id: "confidence-15", number: 135, situation: "not knowing whether my strengths are actually useful" },
      { id: "confidence-16", number: 136, situation: "asking other people for reassurance about every decision" },
      { id: "confidence-17", number: 137, situation: "feeling behind because peers reached a milestone first" },
      { id: "confidence-18", number: 138, situation: "avoiding practice because people might see me being a beginner" },
      { id: "confidence-19", number: 139, situation: "worrying that saying no will make people dislike me" },
      { id: "confidence-20", number: 140, situation: "being afraid of choosing the wrong option" },
    ],
  },
  {
    id: "motivation",
    name: "Motivation & Procrastination",
    followUps: [
      "What is the smallest step I can take now?",
      "How can I make starting easier?",
      "What if I lose motivation again?",
      "How can I make this more consistent?",
    ],
    situations: [
      { id: "motivation-01", number: 141, situation: "knowing what I need to do but repeatedly putting it off" },
      { id: "motivation-02", number: 142, situation: "making detailed plans but rarely following them" },
      { id: "motivation-03", number: 143, situation: "losing motivation after a few productive days" },
      { id: "motivation-04", number: 144, situation: "waiting for the perfect time to start" },
      { id: "motivation-05", number: 145, situation: "having too many goals and constantly switching between them" },
      { id: "motivation-06", number: 146, situation: "scrolling whenever a task becomes difficult" },
      { id: "motivation-07", number: 147, situation: "only becoming productive when a deadline is extremely close" },
      { id: "motivation-08", number: 148, situation: "having a big goal but not knowing the first practical step" },
      { id: "motivation-09", number: 149, situation: "restarting a habit after every missed day" },
      { id: "motivation-10", number: 150, situation: "feeling guilty whenever I relax with unfinished work" },
      { id: "motivation-11", number: 151, situation: "working well at school but struggling at home" },
      { id: "motivation-12", number: 152, situation: "reorganizing notes instead of doing the actual work" },
      { id: "motivation-13", number: 153, situation: "feeling overwhelmed by a huge to-do list" },
      { id: "motivation-14", number: 154, situation: "losing interest in a project halfway through" },
      { id: "motivation-15", number: 155, situation: "watching one more video instead of starting my task" },
      { id: "motivation-16", number: 156, situation: "avoiding a task because it feels boring" },
      { id: "motivation-17", number: 157, situation: "avoiding a task because I am afraid of doing it badly" },
      { id: "motivation-18", number: 158, situation: "calling myself too busy while spending time on low-priority things" },
      { id: "motivation-19", number: 159, situation: "working best late at night even though it disrupts my routine" },
      { id: "motivation-20", number: 160, situation: "losing interest in a goal I used to care about" },
    ],
  },
  {
    id: "time",
    name: "Time Management & Routines",
    followUps: [
      "How should I prioritize it?",
      "What should I change in my routine?",
      "What if the plan gets disrupted?",
      "How can I make the system simpler?",
    ],
    situations: [
      { id: "time-01", number: 161, situation: "being busy all day but not knowing what I actually accomplished" },
      { id: "time-02", number: 162, situation: "underestimating how long almost every task will take" },
      { id: "time-03", number: 163, situation: "balancing school, coaching, hobbies and rest" },
      { id: "time-04", number: 164, situation: "having a weekday routine that collapses on weekends" },
      { id: "time-05", number: 165, situation: "forgetting small tasks until they become urgent" },
      { id: "time-06", number: 166, situation: "having too many things I want to do after school" },
      { id: "time-07", number: 167, situation: "spending too long deciding what to work on" },
      { id: "time-08", number: 168, situation: "having a schedule that looks good but feels exhausting" },
      { id: "time-09", number: 169, situation: "missing deadlines because I forget dates" },
      { id: "time-10", number: 170, situation: "having free time but wasting most of it" },
      { id: "time-11", number: 171, situation: "changing my timetable every few days" },
      { id: "time-12", number: 172, situation: "doing small tasks to avoid an important task" },
      { id: "time-13", number: 173, situation: "leaving home later than I planned" },
      { id: "time-14", number: 174, situation: "forgetting to allow enough travel time" },
      { id: "time-15", number: 175, situation: "wanting a morning routine when mornings are already rushed" },
      { id: "time-16", number: 176, situation: "having a changing schedule that makes fixed study times difficult" },
      { id: "time-17", number: 177, situation: "planning more tasks than I can realistically finish" },
      { id: "time-18", number: 178, situation: "balancing studying with exercise and other activities" },
      { id: "time-19", number: 179, situation: "having my routine collapse whenever something unexpected happens" },
      { id: "time-20", number: 180, situation: "wanting better evenings without making them exhausting" },
    ],
  },
  {
    id: "career",
    name: "Career & Future Decisions",
    followUps: [
      "What information should I gather first?",
      "How can I test the option without committing?",
      "What if I am still uncertain?",
      "How should I make the final decision?",
    ],
    situations: [
      { id: "career-01", number: 181, situation: "having no idea which career direction fits me" },
      { id: "career-02", number: 182, situation: "liking several completely different career fields" },
      { id: "career-03", number: 183, situation: "my family wanting a career path I am unsure about" },
      { id: "career-04", number: 184, situation: "worrying that my subject choice will close future options" },
      { id: "career-05", number: 185, situation: "wondering whether a hobby should become a career" },
      { id: "career-06", number: 186, situation: "being attracted to a career mainly because it is prestigious" },
      { id: "career-07", number: 187, situation: "choosing between salary and personal interest" },
      { id: "career-08", number: 188, situation: "wanting to explore a career without any experience" },
      { id: "career-09", number: 189, situation: "changing my career goal whenever I discover a new field" },
      { id: "career-10", number: 190, situation: "worrying that AI will change the career I want" },
      { id: "career-11", number: 191, situation: "being unsure whether I can handle a very competitive field" },
      { id: "career-12", number: 192, situation: "wanting to build a portfolio but not knowing what projects to make" },
      { id: "career-13", number: 193, situation: "being unsure how much college choice matters" },
      { id: "career-14", number: 194, situation: "feeling pressured to know my whole future while still in school" },
      { id: "career-15", number: 195, situation: "thinking I started learning a field too late" },
      { id: "career-16", number: 196, situation: "considering an opportunity that does not directly match my career goal" },
      { id: "career-17", number: 197, situation: "getting conflicting career advice from different people" },
      { id: "career-18", number: 198, situation: "liking a field but disliking a major part of its daily work" },
      { id: "career-19", number: 199, situation: "researching careers endlessly instead of choosing a direction" },
      { id: "career-20", number: 200, situation: "feeling that choosing one path means losing every other option" },
    ],
  },
  {
    id: "teamwork",
    name: "Group Projects & Teamwork",
    followUps: [
      "What should I say to the group?",
      "How should we divide the work?",
      "What if someone still does not cooperate?",
      "When should a teacher or coordinator be involved?",
    ],
    situations: [
      { id: "teamwork-01", number: 201, situation: "one teammate repeatedly missing their part of our project" },
      { id: "teamwork-02", number: 202, situation: "the group disagreeing about the project's direction" },
      { id: "teamwork-03", number: 203, situation: "one person doing almost all the work" },
      { id: "teamwork-04", number: 204, situation: "a teammate changing decisions after the group agrees" },
      { id: "teamwork-05", number: 205, situation: "starting a project too late and running out of time" },
      { id: "teamwork-06", number: 206, situation: "a teammate having good ideas but not finishing tasks" },
      { id: "teamwork-07", number: 207, situation: "important messages getting lost in the group chat" },
      { id: "teamwork-08", number: 208, situation: "disagreeing with the idea everyone else prefers" },
      { id: "teamwork-09", number: 209, situation: "a teammate taking credit for work I completed" },
      { id: "teamwork-10", number: 210, situation: "project instructions being unclear" },
      { id: "teamwork-11", number: 211, situation: "being assigned a task I do not know how to do" },
      { id: "teamwork-12", number: 212, situation: "a teammate being absent close to the deadline" },
      { id: "teamwork-13", number: 213, situation: "two teammates arguing and stalling the project" },
      { id: "teamwork-14", number: 214, situation: "feeling like my ideas are ignored" },
      { id: "teamwork-15", number: 215, situation: "planning constantly without actually building anything" },
      { id: "teamwork-16", number: 216, situation: "having too many features planned for one project" },
      { id: "teamwork-17", number: 217, situation: "a teammate wanting to submit work with obvious errors" },
      { id: "teamwork-18", number: 218, situation: "doing my part but the overall project still being disorganized" },
      { id: "teamwork-19", number: 219, situation: "having different definitions of what counts as finished" },
      { id: "teamwork-20", number: 220, situation: "being asked to lead a group without wanting to boss people around" },
    ],
  },
  {
    id: "digital",
    name: "Digital Life & Social Media",
    followUps: [
      "What should I do right now?",
      "Should I change any settings or habits?",
      "What if the problem continues?",
      "How can I prevent it next time?",
    ],
    situations: [
      { id: "digital-01", number: 221, situation: "opening social media automatically without intending to" },
      { id: "digital-02", number: 222, situation: "comparing my life with things people post online" },
      { id: "digital-03", number: 223, situation: "checking reactions constantly after posting" },
      { id: "digital-04", number: 224, situation: "feeling pressured to respond instantly in group chats" },
      { id: "digital-05", number: 225, situation: "receiving unwanted messages" },
      { id: "digital-06", number: 226, situation: "sharing something in the wrong chat" },
      { id: "digital-07", number: 227, situation: "spending too much time watching short videos" },
      { id: "digital-08", number: 228, situation: "checking notifications while studying" },
      { id: "digital-09", number: 229, situation: "wanting a social-media break but fearing I will miss things" },
      { id: "digital-10", number: 230, situation: "a friend repeatedly tagging me in posts I dislike" },
      { id: "digital-11", number: 231, situation: "wanting to reply immediately to an angry post" },
      { id: "digital-12", number: 232, situation: "deleting and reposting because I dislike how things look" },
      { id: "digital-13", number: 233, situation: "not knowing whether an online account is trustworthy" },
      { id: "digital-14", number: 234, situation: "seeing someone I know being targeted online" },
      { id: "digital-15", number: 235, situation: "arguing with strangers online" },
      { id: "digital-16", number: 236, situation: "wanting to build something online but fearing judgment" },
      { id: "digital-17", number: 237, situation: "not knowing whether an online message is serious or sarcastic" },
      { id: "digital-18", number: 238, situation: "checking messages repeatedly during homework" },
      { id: "digital-19", number: 239, situation: "wanting to clean up my online presence" },
      { id: "digital-20", number: 240, situation: "spending so much time online that offline activities feel boring" },
    ],
  },
  {
    id: "money",
    name: "Money & Spending",
    followUps: [
      "How should I decide?",
      "What should I check before spending?",
      "What if I cannot afford the option?",
      "How can I avoid repeating the problem?",
    ],
    situations: [
      { id: "money-01", number: 241, situation: "spending small amounts and losing track of where my money went" },
      { id: "money-02", number: 242, situation: "wanting to buy something expensive but not knowing if it is worth it" },
      { id: "money-03", number: 243, situation: "friends often choosing activities I cannot afford" },
      { id: "money-04", number: 244, situation: "regretting an impulsive purchase" },
      { id: "money-05", number: 245, situation: "saving for something but repeatedly spending the money" },
      { id: "money-06", number: 246, situation: "being unsure whether a subscription is worth keeping" },
      { id: "money-07", number: 247, situation: "someone repeatedly asking to borrow money" },
      { id: "money-08", number: 248, situation: "wanting to earn money without hurting my schoolwork" },
      { id: "money-09", number: 249, situation: "saving for several goals and making little progress" },
      { id: "money-10", number: 250, situation: "feeling guilty about spending money on fun" },
      { id: "money-11", number: 251, situation: "being tempted by discounts for things I do not need" },
      { id: "money-12", number: 252, situation: "buying things because my friends have them" },
      { id: "money-13", number: 253, situation: "asking family for money for something important" },
      { id: "money-14", number: 254, situation: "wanting to start budgeting but finding it complicated" },
      { id: "money-15", number: 255, situation: "being unsure whether an online seller is legitimate" },
      { id: "money-16", number: 256, situation: "forgetting small financial commitments" },
      { id: "money-17", number: 257, situation: "wanting to help someone financially despite a limited budget" },
      { id: "money-18", number: 258, situation: "feeling pressure to own expensive things to fit in" },
      { id: "money-19", number: 259, situation: "spending money whenever I am bored" },
      { id: "money-20", number: 260, situation: "choosing between a long-term savings goal and a short-term need" },
    ],
  },
  {
    id: "work",
    name: "Work, Internships & Responsibilities",
    followUps: [
      "How should I communicate this?",
      "What should I prioritize?",
      "What if the other person disagrees?",
      "When should I ask for help?",
    ],
    situations: [
      { id: "work-01", number: 261, situation: "having too many responsibilities and missing small deadlines" },
      { id: "work-02", number: 262, situation: "being new to a role and not knowing what is expected" },
      { id: "work-03", number: 263, situation: "making a mistake on a task" },
      { id: "work-04", number: 264, situation: "being given extra work because I usually say yes" },
      { id: "work-05", number: 265, situation: "being afraid to ask questions at an internship" },
      { id: "work-06", number: 266, situation: "receiving vague instructions" },
      { id: "work-07", number: 267, situation: "waiting for a teammate whose work affects mine" },
      { id: "work-08", number: 268, situation: "balancing a part-time responsibility with school" },
      { id: "work-09", number: 269, situation: "wanting feedback but fearing negative feedback" },
      { id: "work-10", number: 270, situation: "being unsure whether to accept an opportunity with unclear workload" },
      { id: "work-11", number: 271, situation: "procrastinating on boring responsibilities" },
      { id: "work-12", number: 272, situation: "doing work without feeling like I am learning" },
      { id: "work-13", number: 273, situation: "realizing I cannot meet a deadline" },
      { id: "work-14", number: 274, situation: "disagreeing with how a task is being done" },
      { id: "work-15", number: 275, situation: "being nervous about a presentation or meeting" },
      { id: "work-16", number: 276, situation: "being told I am working too slowly" },
      { id: "work-17", number: 277, situation: "wondering whether to ask for more responsibility" },
      { id: "work-18", number: 278, situation: "receiving a work request that crosses a personal boundary" },
      { id: "work-19", number: 279, situation: "worrying that asking for help will make me look incapable" },
      { id: "work-20", number: 280, situation: "choosing between two opportunities with different benefits" },
    ],
  },
  {
    id: "boundaries",
    name: "Conflict & Boundaries",
    followUps: [
      "What boundary should I set?",
      "What words can I use?",
      "What if they ignore the boundary?",
      "When should I involve someone else?",
    ],
    situations: [
      { id: "boundaries-01", number: 281, situation: "someone repeatedly making fun of me and calling it a joke" },
      { id: "boundaries-02", number: 282, situation: "a classmate taking my things without asking" },
      { id: "boundaries-03", number: 283, situation: "someone pressuring me after I already said no" },
      { id: "boundaries-04", number: 284, situation: "a friend becoming angry whenever I disagree" },
      { id: "boundaries-05", number: 285, situation: "being blamed for a problem I did not cause" },
      { id: "boundaries-06", number: 286, situation: "being caught between two people who are angry" },
      { id: "boundaries-07", number: 287, situation: "someone repeatedly talking over me" },
      { id: "boundaries-08", number: 288, situation: "a friend expecting me to be available constantly" },
      { id: "boundaries-09", number: 289, situation: "someone asking for personal information I do not want to share" },
      { id: "boundaries-10", number: 290, situation: "a group pressuring me to agree with them" },
      { id: "boundaries-11", number: 291, situation: "not knowing whether to reach out after an argument" },
      { id: "boundaries-12", number: 292, situation: "someone changing the rules of an agreement" },
      { id: "boundaries-13", number: 293, situation: "agreeing to something and later realizing I cannot do it" },
      { id: "boundaries-14", number: 294, situation: "worrying that setting a boundary will seem rude" },
      { id: "boundaries-15", number: 295, situation: "someone spreading an untrue story about me" },
      { id: "boundaries-16", number: 296, situation: "someone repeatedly trying to pull me into an argument" },
      { id: "boundaries-17", number: 297, situation: "needing to tell someone that repeated behavior is not okay" },
      { id: "boundaries-18", number: 298, situation: "feeling guilty after setting a reasonable boundary" },
      { id: "boundaries-19", number: 299, situation: "seeing someone being excluded and wanting to help" },
      { id: "boundaries-20", number: 300, situation: "having the same conflict repeat after every apology" },
    ],
  },
  {
    id: "wellbeing",
    name: "Wellbeing & Healthy Routines",
    followUps: [
      "What small change can I make first?",
      "How can I make it easier to maintain?",
      "What if it does not improve?",
      "When should I talk to a trusted adult or professional?",
    ],
    situations: [
      { id: "wellbeing-01", number: 301, situation: "feeling tired during the day and struggling with schoolwork" },
      { id: "wellbeing-02", number: 302, situation: "having a very late sleep schedule on weekends" },
      { id: "wellbeing-03", number: 303, situation: "sitting for long periods while studying" },
      { id: "wellbeing-04", number: 304, situation: "skipping meals because my schedule is busy" },
      { id: "wellbeing-05", number: 305, situation: "wanting to become more physically active but lacking consistency" },
      { id: "wellbeing-06", number: 306, situation: "feeling stressed before school without a clear reason" },
      { id: "wellbeing-07", number: 307, situation: "finding it difficult to relax because I feel I should be productive" },
      { id: "wellbeing-08", number: 308, situation: "using my phone late at night even when I want to sleep" },
      { id: "wellbeing-09", number: 309, situation: "feeling overwhelmed by school and everyday responsibilities" },
      { id: "wellbeing-10", number: 310, situation: "having trouble concentrating when tired or stressed" },
      { id: "wellbeing-11", number: 311, situation: "wanting a healthier routine without changing everything at once" },
      { id: "wellbeing-12", number: 312, situation: "feeling guilty when I take a day away from my routine" },
      { id: "wellbeing-13", number: 313, situation: "feeling mentally overloaded and unable to focus" },
      { id: "wellbeing-14", number: 314, situation: "starting healthy routines enthusiastically and then abandoning them" },
      { id: "wellbeing-15", number: 315, situation: "wanting more energy during long study sessions" },
      { id: "wellbeing-16", number: 316, situation: "feeling unusually stressed for several weeks" },
      { id: "wellbeing-17", number: 317, situation: "using entertainment to avoid stressful responsibilities" },
      { id: "wellbeing-18", number: 318, situation: "having no time left for things I enjoy" },
      { id: "wellbeing-19", number: 319, situation: "slipping back into an old habit after trying to change it" },
      { id: "wellbeing-20", number: 320, situation: "not knowing when stress is something I should ask for help with" },
    ],
  },
  {
    id: "coding",
    name: "Technology & Coding Projects",
    followUps: [
      "What should I check first?",
      "How can I isolate the problem?",
      "What is the smallest safe change?",
      "How should I test it afterward?",
    ],
    situations: [
      { id: "coding-01", number: 321, situation: "having a coding idea but not knowing how to start" },
      { id: "coding-02", number: 322, situation: "code working for some inputs but failing for others" },
      { id: "coding-03", number: 323, situation: "adding features before finishing the basic version" },
      { id: "coding-04", number: 324, situation: "copying a solution without fully understanding it" },
      { id: "coding-05", number: 325, situation: "trying the same bug fix repeatedly without progress" },
      { id: "coding-06", number: 326, situation: "wanting to learn a new programming language with unfinished projects" },
      { id: "coding-07", number: 327, situation: "having a project that works but feels slow" },
      { id: "coding-08", number: 328, situation: "worrying about exposing an API key in frontend code" },
      { id: "coding-09", number: 329, situation: "trying to deploy a project and hitting configuration issues" },
      { id: "coding-10", number: 330, situation: "having too many dependencies and not knowing which matter" },
      { id: "coding-11", number: 331, situation: "using AI coding tools and worrying I am not learning enough" },
      { id: "coding-12", number: 332, situation: "having an app work locally but fail after deployment" },
      { id: "coding-13", number: 333, situation: "adding a feature without wanting to break existing behavior" },
      { id: "coding-14", number: 334, situation: "polishing UI instead of finishing core functionality" },
      { id: "coding-15", number: 335, situation: "not knowing whether an error comes from my code or an external service" },
      { id: "coding-16", number: 336, situation: "wanting a project to look professional for a demonstration" },
      { id: "coding-17", number: 337, situation: "being afraid to change a complicated project" },
      { id: "coding-18", number: 338, situation: "switching frameworks because another one looks better" },
      { id: "coding-19", number: 339, situation: "wanting to publish a project without exposing private information" },
      { id: "coding-20", number: 340, situation: "having a working project but struggling to explain it clearly" },
    ],
  },
  {
    id: "everyday",
    name: "Everyday Decisions & Small Problems",
    followUps: [
      "What should I decide first?",
      "What information actually matters?",
      "What if both options remain reasonable?",
      "How can I avoid the same problem next time?",
    ],
    situations: [
      { id: "everyday-01", number: 341, situation: "having several errands and very little free time" },
      { id: "everyday-02", number: 342, situation: "forgetting something important at home after leaving" },
      { id: "everyday-03", number: 343, situation: "having two plans at the same time" },
      { id: "everyday-04", number: 344, situation: "agreeing to help someone and then becoming overloaded" },
      { id: "everyday-05", number: 345, situation: "asking everyone else for opinions before every decision" },
      { id: "everyday-06", number: 346, situation: "being unsure whether to replace something that still works" },
      { id: "everyday-07", number: 347, situation: "forgetting where I put important things" },
      { id: "everyday-08", number: 348, situation: "choosing between doing something now or waiting" },
      { id: "everyday-09", number: 349, situation: "being unsure whether to attend an event because I am tired" },
      { id: "everyday-10", number: 350, situation: "agreeing to plans and later wishing I had stayed home" },
      { id: "everyday-11", number: 351, situation: "choosing a gift when I do not know what the person wants" },
      { id: "everyday-12", number: 352, situation: "needing directions or help in an unfamiliar place" },
      { id: "everyday-13", number: 353, situation: "making a small public mistake and feeling embarrassed" },
      { id: "everyday-14", number: 354, situation: "postponing a tiny task because it is annoying" },
      { id: "everyday-15", number: 355, situation: "choosing whether to repair, replace or keep using something" },
      { id: "everyday-16", number: 356, situation: "wanting to join an activity where I know nobody" },
      { id: "everyday-17", number: 357, situation: "having too many small unfinished tasks" },
      { id: "everyday-18", number: 358, situation: "changing a plan because something unexpected happened" },
      { id: "everyday-19", number: 359, situation: "always choosing the easiest option and later regretting it" },
      { id: "everyday-20", number: 360, situation: "being stuck between two reasonable choices" },
    ],
  },
  {
    id: "organization",
    name: "Organization & Personal Systems",
    followUps: [
      "What should I organize first?",
      "How can I keep the system simple?",
      "What can I ignore or archive?",
      "How can I stop the mess returning?",
    ],
    situations: [
      { id: "organization-01", number: 361, situation: "having files and notes scattered across different places" },
      { id: "organization-02", number: 362, situation: "creating lists but forgetting to check them" },
      { id: "organization-03", number: 363, situation: "my desk becoming messy whenever I get busy" },
      { id: "organization-04", number: 364, situation: "having duplicate notes for the same subject" },
      { id: "organization-05", number: 365, situation: "losing track of project versions" },
      { id: "organization-06", number: 366, situation: "having too many browser tabs open" },
      { id: "organization-07", number: 367, situation: "saving everything because I might need it someday" },
      { id: "organization-08", number: 368, situation: "organizing every subject differently" },
      { id: "organization-09", number: 369, situation: "having a huge backlog of digital files to sort" },
      { id: "organization-10", number: 370, situation: "losing useful links because I cannot remember where I saved them" },
      { id: "organization-11", number: 371, situation: "having a project folder full of old drafts" },
      { id: "organization-12", number: 372, situation: "losing track of deadlines across school and personal projects" },
      { id: "organization-13", number: 373, situation: "forgetting recurring tasks" },
      { id: "organization-14", number: 374, situation: "creating elaborate productivity systems instead of doing work" },
      { id: "organization-15", number: 375, situation: "having detailed notes that are hard to review" },
      { id: "organization-16", number: 376, situation: "not knowing what information is worth saving" },
      { id: "organization-17", number: 377, situation: "having too many apps for the same purpose" },
      { id: "organization-18", number: 378, situation: "receiving too many unnecessary messages" },
      { id: "organization-19", number: 379, situation: "starting organization projects and never finishing them" },
      { id: "organization-20", number: 380, situation: "wanting a calmer digital workspace" },
    ],
  },
  {
    id: "learning",
    name: "Learning & Skill Building",
    followUps: [
      "What should I practice first?",
      "How can I tell whether I am improving?",
      "What if I get stuck?",
      "When should I move to something harder?",
    ],
    situations: [
      { id: "learning-01", number: 381, situation: "not knowing which resources to trust for learning a skill" },
      { id: "learning-02", number: 382, situation: "understanding tutorials but struggling without them" },
      { id: "learning-03", number: 383, situation: "learning theory without applying it" },
      { id: "learning-04", number: 384, situation: "feeling that progress is too slow" },
      { id: "learning-05", number: 385, situation: "trying to learn too many skills at once" },
      { id: "learning-06", number: 386, situation: "switching tutorials whenever another one looks better" },
      { id: "learning-07", number: 387, situation: "following examples but struggling independently" },
      { id: "learning-08", number: 388, situation: "having very limited time to learn" },
      { id: "learning-09", number: 389, situation: "not knowing what to memorize versus understand" },
      { id: "learning-10", number: 390, situation: "forgetting what I learned after a few weeks" },
      { id: "learning-11", number: 391, situation: "wanting to build a portfolio while learning" },
      { id: "learning-12", number: 392, situation: "getting frustrated when something does not click quickly" },
      { id: "learning-13", number: 393, situation: "not knowing whether I am ready for harder material" },
      { id: "learning-14", number: 394, situation: "practicing only what I already find easy" },
      { id: "learning-15", number: 395, situation: "repeating the same mistakes" },
      { id: "learning-16", number: 396, situation: "having many AI tools available and not knowing how to use them for learning" },
      { id: "learning-17", number: 397, situation: "learning alone without anyone to give feedback" },
      { id: "learning-18", number: 398, situation: "collecting certificates instead of building real skill" },
      { id: "learning-19", number: 399, situation: "losing interest in a skill I started learning" },
      { id: "learning-20", number: 400, situation: "feeling impatient about how long mastery takes" },
    ],
  },
  {
    id: "decisions",
    name: "Decision Making & Uncertainty",
    followUps: [
      "What information matters most?",
      "What can I control?",
      "Can I test the decision first?",
      "When should I stop analyzing and choose?",
    ],
    situations: [
      { id: "decisions-01", number: 401, situation: "having two good options and constantly going back and forth" },
      { id: "decisions-02", number: 402, situation: "needing to decide with incomplete information" },
      { id: "decisions-03", number: 403, situation: "knowing what I want but fearing the consequences" },
      { id: "decisions-04", number: 404, situation: "receiving conflicting advice from everyone around me" },
      { id: "decisions-05", number: 405, situation: "making a decision and then reconsidering it repeatedly" },
      { id: "decisions-06", number: 406, situation: "choosing between something useful now and something potentially better later" },
      { id: "decisions-07", number: 407, situation: "being afraid of regretting whichever option I choose" },
      { id: "decisions-08", number: 408, situation: "making a decision mainly to avoid disappointing someone" },
      { id: "decisions-09", number: 409, situation: "focusing too much on everything that could go wrong" },
      { id: "decisions-10", number: 410, situation: "not knowing whether to wait for more information" },
      { id: "decisions-11", number: 411, situation: "making a decision that affects another person too" },
      { id: "decisions-12", number: 412, situation: "choosing between a safe option and an uncertain opportunity" },
      { id: "decisions-13", number: 413, situation: "making a quick decision and then worrying it was careless" },
      { id: "decisions-14", number: 414, situation: "delaying a decision because there is no perfect answer" },
      { id: "decisions-15", number: 415, situation: "asking for reassurance even after deciding" },
      { id: "decisions-16", number: 416, situation: "choosing priorities when everything feels important" },
      { id: "decisions-17", number: 417, situation: "not knowing whether a problem needs action or time" },
      { id: "decisions-18", number: 418, situation: "making the same type of poor decision repeatedly" },
      { id: "decisions-19", number: 419, situation: "wanting to make a major change without testing the idea" },
      { id: "decisions-20", number: 420, situation: "feeling stuck because every option has a downside" },
    ],
  },
  {
    id: "romance",
    name: "Romance, Crushes & Social Feelings",
    followUps: [
      "What do I actually know?",
      "How can I keep things low-pressure and respectful?",
      "What if they do not feel the same?",
      "How can I move forward without overthinking?",
    ],
    situations: [
      { id: "romance-01", number: 421, situation: "liking someone and not knowing whether to tell them" },
      { id: "romance-02", number: 422, situation: "having a crush on an existing friend" },
      { id: "romance-03", number: 423, situation: "not knowing whether someone wants friendship or something more" },
      { id: "romance-04", number: 424, situation: "sending an awkward message to someone I like" },
      { id: "romance-05", number: 425, situation: "someone I like not seeming to respond with the same energy" },
      { id: "romance-06", number: 426, situation: "being nervous about talking to someone I have a crush on" },
      { id: "romance-07", number: 427, situation: "thinking I may have hurt someone's feelings" },
      { id: "romance-08", number: 428, situation: "a friend repeatedly teasing me about liking someone" },
      { id: "romance-09", number: 429, situation: "feeling jealous when someone I like talks to others" },
      { id: "romance-10", number: 430, situation: "wondering whether to invite someone to hang out one-on-one" },
      { id: "romance-11", number: 431, situation: "someone saying they are not interested and me struggling to move forward" },
      { id: "romance-12", number: 432, situation: "thinking a friend may like me when I do not feel the same" },
      { id: "romance-13", number: 433, situation: "wanting to tell a friend about my feelings for someone else" },
      { id: "romance-14", number: 434, situation: "checking constantly whether someone has viewed my message" },
      { id: "romance-15", number: 435, situation: "worrying rejection will make future interactions awkward" },
      { id: "romance-16", number: 436, situation: "supporting someone who is receiving unwanted romantic attention" },
      { id: "romance-17", number: 437, situation: "feeling pressured by friends to be in a relationship" },
      { id: "romance-18", number: 438, situation: "being unsure whether an online interaction is genuine" },
      { id: "romance-19", number: 439, situation: "imagining a future with someone I barely know" },
      { id: "romance-20", number: 440, situation: "feeling upset after a friendship or crush changes unexpectedly" },
    ],
  },
  {
    id: "creative",
    name: "Creative Projects & Hobbies",
    followUps: [
      "What is the smallest version I can make?",
      "How can I stop overthinking it?",
      "What if I receive criticism?",
      "How can I actually finish it?",
    ],
    situations: [
      { id: "creative-01", number: 441, situation: "having a creative idea but being afraid it will not be good enough" },
      { id: "creative-02", number: 442, situation: "starting creative projects but rarely finishing them" },
      { id: "creative-03", number: 443, situation: "having too many hobbies and not enough time" },
      { id: "creative-04", number: 444, situation: "comparing my creative work with professionals" },
      { id: "creative-05", number: 445, situation: "wanting to share something I created but fearing criticism" },
      { id: "creative-06", number: 446, situation: "continuously improving a project instead of finishing it" },
      { id: "creative-07", number: 447, situation: "losing interest in a hobby I used to love" },
      { id: "creative-08", number: 448, situation: "feeling intimidated by people who are much better at a creative skill" },
      { id: "creative-09", number: 449, situation: "wanting to publish a personal project but not knowing if it is ready" },
      { id: "creative-10", number: 450, situation: "collecting ideas instead of choosing one" },
      { id: "creative-11", number: 451, situation: "wanting to collaborate but fearing loss of control" },
      { id: "creative-12", number: 452, situation: "receiving harsh feedback on something I created" },
      { id: "creative-13", number: 453, situation: "being stuck creatively and unable to start" },
      { id: "creative-14", number: 454, situation: "having an idea but not knowing how difficult it is technically" },
      { id: "creative-15", number: 455, situation: "wanting to turn a hobby into a portfolio" },
      { id: "creative-16", number: 456, situation: "abandoning projects whenever a difficult part appears" },
      { id: "creative-17", number: 457, situation: "having very limited time for a creative project" },
      { id: "creative-18", number: 458, situation: "considering buying equipment for a hobby" },
      { id: "creative-19", number: 459, situation: "feeling guilty about hobbies during a busy academic period" },
      { id: "creative-20", number: 460, situation: "wanting to demonstrate a project at an exhibition" },
    ],
  },
  {
    id: "growth",
    name: "Personal Growth & Life Direction",
    followUps: [
      "What matters most right now?",
      "What is one action I can take this week?",
      "What should I stop trying to fix at once?",
      "How can I review my progress?",
    ],
    situations: [
      { id: "growth-01", number: 461, situation: "doing many things but not feeling that I am moving toward anything meaningful" },
      { id: "growth-02", number: 462, situation: "wanting to become more disciplined without knowing what to change first" },
      { id: "growth-03", number: 463, situation: "feeling stuck in the same routine" },
      { id: "growth-04", number: 464, situation: "setting goals based mostly on what other people expect" },
      { id: "growth-05", number: 465, situation: "not knowing what values actually matter most to me" },
      { id: "growth-06", number: 466, situation: "wanting to become more reliable" },
      { id: "growth-07", number: 467, situation: "feeling like I need to improve everything at once" },
      { id: "growth-08", number: 468, situation: "wanting more independence while still needing support" },
      { id: "growth-09", number: 469, situation: "constantly starting new self-improvement systems" },
      { id: "growth-10", number: 470, situation: "worrying I am wasting my teenage years by focusing too much on work" },
      { id: "growth-11", number: 471, situation: "feeling pressure to have a clear identity already" },
      { id: "growth-12", number: 472, situation: "wanting to make better decisions instead of reacting emotionally" },
      { id: "growth-13", number: 473, situation: "thinking about who I want to become but struggling to act accordingly" },
      { id: "growth-14", number: 474, situation: "wanting to depend less on other people's approval" },
      { id: "growth-15", number: 475, situation: "feeling uncertain about whether I am making progress in life" },
      { id: "growth-16", number: 476, situation: "wanting to handle failure better" },
      { id: "growth-17", number: 477, situation: "changing interests and feeling like I am losing direction" },
      { id: "growth-18", number: 478, situation: "wanting to be more consistent with promises I make to myself" },
      { id: "growth-19", number: 479, situation: "being unsure whether to simplify my life or take on more opportunities" },
      { id: "growth-20", number: 480, situation: "wanting to look back in a year and feel that I genuinely grew" },
    ],
  },
  {
    id: "life-skills",
    name: "Practical Life Skills",
    followUps: [
      "What should I learn first?",
      "How can I practice it safely?",
      "What if I get stuck?",
      "How can I make it a repeatable habit?",
    ],
    situations: [
      { id: "life-skills-01", number: 481, situation: "wanting to learn a few basic meals" },
      { id: "life-skills-02", number: 482, situation: "needing to organize important documents" },
      { id: "life-skills-03", number: 483, situation: "wanting to communicate better with adults" },
      { id: "life-skills-04", number: 484, situation: "forgetting basic household tasks" },
      { id: "life-skills-05", number: 485, situation: "wanting to plan a simple trip responsibly" },
      { id: "life-skills-06", number: 486, situation: "being nervous about making an appointment or service call" },
      { id: "life-skills-07", number: 487, situation: "wanting to become better at keeping commitments" },
      { id: "life-skills-08", number: 488, situation: "not knowing whom to ask for help with a practical problem" },
      { id: "life-skills-09", number: 489, situation: "wanting to learn basic computer maintenance safely" },
      { id: "life-skills-10", number: 490, situation: "losing chargers, cables and small accessories" },
      { id: "life-skills-11", number: 491, situation: "wanting to prepare for school the night before" },
      { id: "life-skills-12", number: 492, situation: "balancing personal responsibilities with helping family" },
      { id: "life-skills-13", number: 493, situation: "wanting to compare products before buying them" },
      { id: "life-skills-14", number: 494, situation: "forgetting to back up important digital work" },
      { id: "life-skills-15", number: 495, situation: "wanting to be better prepared for unexpected problems" },
      { id: "life-skills-16", number: 496, situation: "not knowing how to ask for a refund or correction" },
      { id: "life-skills-17", number: 497, situation: "struggling to explain a practical problem clearly" },
      { id: "life-skills-18", number: 498, situation: "forgetting passwords and account recovery details" },
      { id: "life-skills-19", number: 499, situation: "wanting to plan a week without making an unrealistic schedule" },
      { id: "life-skills-20", number: 500, situation: "wanting to solve small problems without immediately panicking" },
    ],
  },
];

export const REFERENCE_CATEGORIES: readonly ReferenceCategory[] = DATASET.map(({ id, name, followUps }) => ({ id, name, followUps }));

/** All 500 situations, in the document's order. */
export const REFERENCE_SITUATIONS: readonly ReferenceSituation[] = DATASET.flatMap((source, index) => {
  const category = REFERENCE_CATEGORIES[index];
  return source.situations.map((entry) => ({ ...entry, category, followUps: category.followUps }));
});
